# fly.toml app configuration file generated for japicmp-backend on 2023-11-17T10:48:48+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "japicmp-backend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
